### ISSUE TITLE
StartTimestamp Param

### ISSUE THREAD

**Issue by KireBinn** [datacrunch-com/datacrunch-contracts#12]
Hi

I'm closely following the updates on this contract

Instead of this function

function begin() external onlyOwner onlyWhenNotStarted {
        startDate = block.timestamp;

Why not add StartTimestamp Param?

This will enable Devs to allow vesting start from the past as "Initial Release"

This is more ideal 

Thanks

**Comment by Caceresenzo** [comment]
This is a good idea.
Thanks you.

The contract is actually going under a partial rewrite to allow a person to have multiple vesting.
I will keep you updated when I can do this change.

**Comment by KireBinn** [comment]
Sounds great however how about having these features

Vest
@Param _beneficiary
@Param _amount
@Param _duration
@Param _SlicePeriod/Interval (seconds)
@Param _StartTimestamp
@Param -Cliff(Seconds)
@Param _revocable

Note
Vesting starts at StartTimestamp with optional cliff.
=========
SlicePeriod/ Interval is important as this will give this contract much flexibility to be used for Monthly, weekly or daily VestingSchedule. For instance, a 5monthsVesting( released monthly) will have 20% vest monthly.
That is
_duration = 5months = 12960000 seconds
_SlicePeriod = 30days = 2592000

This can easily be turned to weekly or daily or hourly vesting contract by changing the SlicePeriod
============

Another in demand feature is ability to vest multiple addresses at once. saves gas and time. Let's say you have 1000 addresses to Vest

MulitiVest
@Param _beneficiary [ ]
@Param _amount [ ]
@Param _duration
@Param _SlicePeriod/Interval (seconds)
@Param _StartTimestamp
@Param -Cliff(Seconds)
@Param _revocable

===============
Another on-demand feature is ability to withdraw all vested tokens at once. Most Users allow their for tokens to vest for atleast 2-3 periods before withdrawing.

In most use cases, this is used rather than having more than one vesting IDs. A Claim Function should release all vested CRUNCHs

================

I'm confident this contract will receive multiple Forks if we can get these features

**Comment by Caceresenzo** [comment]
That a lot of things you got there, let's take them one by one.

> Vest
> @param _beneficiary
> @param _amount
> @param _duration
> @param _SlicePeriod/Interval (seconds)
> @param _StartTimestamp
> @param -Cliff(Seconds)
> @param _revocable

Seems like you copy-pasted it from elsewhere.
Our contract does not have a `_StartTimestamp` per vesting. It will be a global start for everyone.
This method has already been done. Only the name is really different. (currently called `create`, I agree that `vest` is a way better name)

> SlicePeriod/ Interval is important as this will give this contract much flexibility to be used for Monthly, weekly or daily VestingSchedule. For instance, a 5monthsVesting( released monthly) will have 20% vest monthly.
> That is
> _duration = 5months = 12960000 seconds
> _SlicePeriod = 30days = 2592000

The original implementation is based on [OpenZeppelin's vesting draft](https://github.com/binodnp/openzeppelin-solidity/blob/master/contracts/drafts/TokenVesting.sol) and does not have any "period" mechanism.
The tokens are always claimable.

For the example you have provided: you will be able to claim **up to** 20% vest monthly. But you will able to claim only 5% per week if you want (as for 4 weeks = 1 month). If you didn't wait enough time between two claim, you will just receive an error "no tokens are due".

> Another in demand feature is ability to vest multiple addresses at once. saves gas and time. Let's say you have 1000 addresses to Vest

This vesting contract will not be used for a lot of people, but I do understand the use case.
We planned to add staking for vested tokens but it was conflicting with a lot of things.
The current rewrite is now able to handle the ability of having multiple vesting.

> Another on-demand feature is ability to withdraw all vested tokens at once. Most Users allow their for tokens to vest for atleast 2-3 periods before withdrawing.
> 
> In most use cases, this is used rather than having more than one vesting IDs. A Claim Function should release all vested CRUNCHs

This was originally in the first version of the contract but was scrapped because it was conflicting with the staking.
Since we will not add the staking, I will add it back!

> I'm confident this contract will receive multiple Forks if we can get these features

Thanks :)
But for now we are more concentrated on what the project need instead of making a universal solution that anyone can use.

**Comment by Caceresenzo** [comment]
Since I have completed this issue's original request, I will close it.
Please open an issue per request if you need more things.

**Comment by KireBinn** [comment]
Alright. Looking forward to what you guys come up with
